modLoader="javafml"
loaderVersion="[28,)"
#updateJSONURL=""
#issueTrackerURL=""
#displayURL=""
#logoFile="logo.png"
[[mods]]
modId="eyesinthedarkness"
version="${file.jarVersion}"
displayName="Eyes in the Darkness"
credits="The Forge and FML guys, for making the awesome modding environment"
authors="gigaherz"
description='''
Those eyes you think you saw when walking through the forest at night. No, you did not imagine them.
'''
[[dependencies.eyesinthedarkness]]
   modId="forge"
   mandatory=true
   versionRange="[28.1.0,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.eyesinthedarkness]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.14.4,1.15)"
   ordering="NONE"
   side="BOTH"